### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by peet86** [therufa/mdi-vue#41]
Please add support for legacy - but still in use - browsers like IE11. Currently the library throws syntax error in IE11. It seems something is off in mdi-vue/browser-c94fd32b.js

**Comment by therufa** [comment]
oh no! what a nightmare! thanks for reporting this issue, I'll get to it ASAP

**Comment by peet86** [comment]
Ohh, thank you Sir, you are very kind Sir!

**Comment by therufa** [comment]
So after a little investigation, it seems that the issue lays in the build tools we have. A proven solution would be to include the vue icon components instead of the transpiled ones. Meaning, you should import files using the `.vue` extension as in `Cog.vue` or `Home.vue` etc. 
This is the best I've found, for now.
